### ISSUE TITLE
'clip' is not defined

### ISSUE THREAD

**Issue by theChaosCoder** [WolframRhodium/muvsfunc#1]
I tried some of the aa functions, but got an error everytime  'clip' is not defined.
I'm using the latest vapoursynth version R35 x64

```
muvsfunc.py", line 731, in nnedi3aa
last = core.fmtc.resample(last, a.width, a.height, [-0.5, -0.5 * (1 NameError: name 'clip' is not defined
```

```
muvsfunc.py", line 712, in ediaa
last = core.fmtc.resample(last, a.width, a.height, [-0.5, -0.5 * (1 NameError: name 'clip' is not defined
```

It's this line
`last = core.fmtc.resample(last, a.width, a.height, [-0.5, -0.5 * (1 << clip.format.subsampling_w)], [-0.5, -0.5 * (1 << clip.format.subsampling_h)], kernel='spline36')
`

I think it should be  1<< a.format .... since the clip name is a "def nnedi3aa(a):"

**Comment by WolframRhodium** [comment]
Thank you for your reminder, I made a stupid mistake.
These errors should have been fixed.
