### ISSUE TITLE
SeeSaw limit

### ISSUE THREAD

**Issue by Helenerineium** [WolframRhodium/muvsfunc#13]
When `Slimit < 0`, the sharpdiff is normalized to 8-bit range before doing `pow(diff,1/abs(limit))`
So `SLIM` used don't need to scale by bit depth when `Slimit < 0`
`SLIM = scale(Slimit, peak) if Slimit >= 0 else abs(Slimit)` should solve this problem.

**Comment by WolframRhodium** [comment]
https://github.com/WolframRhodium/muvsfunc/commit/d181c4b44659975ecb6b7b829f21abfbd4c4ba06

thx

**Comment by Helenerineium** [comment]
Uh... A copy-paste error here, your scale function is `scale(value, bits)`, also `peak` is undefined in your main function (though not needed)
