### ISSUE TITLE
MDSI Expr: Failed to convert 'inf' to float

### ISSUE THREAD

**Issue by Ken1256** [WolframRhodium/muvsfunc#18]
```
2019-02-09 03:42:41.410
Error on frame 2585 request:
Expr: Failed to convert 'inf' to float
2019-02-09 03:42:43.545
Error on frame 5687 request:
Expr: Failed to convert 'inf' to float
Error on frame 11891 request:
Expr: Failed to convert 'inf' to float
Error on frame 15897 request:
Expr: Failed to convert 'inf' to float
Error on frame 19258 request:
Expr: Failed to convert 'inf' to float
Error on frame 22360 request:
Expr: Failed to convert 'inf' to float
Error on frame 26625 request:
Expr: Failed to convert 'inf' to float
Error on frame 29856 request:
Expr: Failed to convert 'inf' to float
Error on frame 37998 request:
Expr: Failed to convert 'inf' to float
Error on frame 49243 request:
Expr: Failed to convert 'inf' to float
Error on frame 55317 request:
Expr: Failed to convert 'inf' to float
2019-02-09 03:42:58.594
Error on frame 41102 request:
Expr: Failed to convert 'inf' to float
Error on frame 41102 request:
Expr: Failed to convert 'inf' to float
Error on frame 41099 request:
Expr: Failed to convert 'inf' to float
Error on frame 41099 request:
Expr: Failed to convert 'inf' to float
Error on frame 41102 request:
Expr: Failed to convert 'inf' to float
2019-02-09 03:43:05.610
Error on frame 144109 request:
Expr: Failed to convert 'inf' to float
Error on frame 148504 request:
Expr: Failed to convert 'inf' to float
Error on frame 153932 request:
Expr: Failed to convert 'inf' to float
2019-02-09 03:43:11.504
Error on frame 165822 request:
Expr: Failed to convert 'inf' to float
Error on frame 169829 request:
Expr: Failed to convert 'inf' to float
2019-02-09 03:43:33.898
Error on frame 54800 request:
Expr: Failed to convert 'inf' to float
Error on frame 42780 request:
Expr: Failed to convert 'inf' to float
Error on frame 34379 request:
Expr: Failed to convert 'inf' to float
2019-02-09 03:43:37.734
Error on frame 70956 request:
Expr: Failed to convert 'inf' to float
```

**Comment by WolframRhodium** [comment]
Did you use the latest version? (Commit [bbdac46](https://github.com/WolframRhodium/muvsfunc/commit/bbdac4695c99e686222f537ab201290e36f3788f))

**Comment by Ken1256** [comment]
51043ef,  Commit bbdac46 solve the problem.
Other question KNLMeasCL_cupy if Temporal part done will faster than KNLMeasCL OpenCL?(e.g d=2)
Thanks

**Comment by WolframRhodium** [comment]
Maybe the CuPy version could run faster than the OpenCL version if I further optimize the code, but it seems that my implementation runs a bit slower than the OpenCL version, maybe because I didn't take advantage of CUDA and/or the OpenCL has been fully optimized and it's hard to optimize further.

The CuPy version currently makes it easier for me to experiment with various ideas and practice programming.

**Comment by Ken1256** [comment]
Maybe add Dither_bilateral16 subspl and thr can skip some process to speed up KNLMeasCL?
Dither_bilateral16, warpsharp need avsproxy pass to VapourSynth it slow but simple and effective.

**Comment by WolframRhodium** [comment]
[Here](https://github.com/dubhater/vapoursynth-awarpsharp2) is the native implementation of awarpsharp2 in VapourSynth.

`subspl` will certainly be useful in reducing the number of memory operations, and numerous other acceleration techniques exist (e.g. [a fast approximation in OpenCV](https://github.com/opencv/opencv/blob/48432502b6fe166242a25e1f9cc1d7215a72c1bb/modules/photo/src/cuda/nlm.cu#L178)). I will check them later.

**Comment by Ken1256** [comment]
In my test warpsharp/Dither_bilateral16 must better than VapourSynth awarpsharp2/VapourSynth-BilateralGPU, I think it is completely different filters.
