### ISSUE TITLE
 'origsuper' is not defined in SharpAAMcmod

### ISSUE THREAD

**Issue by theChaosCoder** [WolframRhodium/muvsfunc#2]
Found another bug:

```
muvsfunc.py", line 842, in SharpAAMcmod
fv2 = core.mv.Analyse(origsuper, isb=False, delta=2, overlap=aaov, blksize=aablk) if tradius >= 2 else None
NameError: name 'origsuper' is not defined
```

My function  call
clip = muv.SharpAAMcmod(clip,dark	=  0.4 ,thin	= 1 ,sharp	= 50 ,smooth	=   -1, stabilize =True, aapel = 4, aablk = 4, aaov=4, aatype = "sangnom")

It works with stabilize = False

**Comment by WolframRhodium** [comment]
It has been fixed.
Once again, thank you very much for your reminder.
