### ISSUE TITLE
TypeError: GradFun3: "thr" must be an int or a float!

### ISSUE THREAD

**Issue by dubhater** [WolframRhodium/muvsfunc#20]
Hi.

I'm getting this error with the current git master version. This is the call:
```python
deband = muvsfunc.GradFun3(src=nr16, thr=0.25, radius=12, smode=2, mask=0, ampn=0, lsb=True)
```

GradFun3 always raises this error if thr is not None. The type check is missing.

**Comment by WolframRhodium** [comment]
Hi,

thank you for your report. The problem should be solved now.

**Comment by dubhater** [comment]
Thanks!
