### ISSUE TITLE
YAHRmask

### ISSUE THREAD

**Issue by nobananasforyou** [WolframRhodium/muvsfunc#22]
Hello, 

Could you please port the function YAHRmask. It preserves more detail than the other YAHR variants. 

Thank you!

Script: https://pastebin.com/raw/LUErwWR8

**Comment by WolframRhodium** [comment]
Done. https://github.com/WolframRhodium/muvsfunc/commit/8daf70f61d277bf3347b4ddffc31f138c24bab6c
