### ISSUE TITLE
dfttestMC with mdg=True makes image brighter 

### ISSUE THREAD

**Issue by Ryuukishi** [WolframRhodium/muvsfunc#28]
[link to comparison](https://slow.pics/c/DhS8UCRp)

The code I used to replicate the issue:

```
src16 = core.fmtc.bitdepth(src,bits=16)
denoise = muf.dfttestMC(src16,mdg=True)
denoise.set_output()
```

I've tested with multiple sources and they all have the same issue when mdg=True. Any ideas why?

**Comment by WolframRhodium** [comment]
Thanks for the report and the solution. It should be fixed now.
