### ISSUE TITLE
GuidedFilter bug

### ISSUE THREAD

**Issue by Z4ST1N** [WolframRhodium/muvsfunc#4]
Most likely in Line 2987, the filter attempts to divide by zero.
`kk = -4 / (frameMin - alpha)`
It happened on a black frame about 1200 frames into an encode I had running, and disabling the GuidedFilter line allowed me to preview it

**Comment by WolframRhodium** [comment]
Confirmed. Please try the latest commit.

**Comment by Z4ST1N** [comment]
Yep, it encoded without issue this time
