### ISSUE TITLE
YAHRmask Bug

### ISSUE THREAD

**Issue by nobananasforyou** [WolframRhodium/muvsfunc#45]
G'day!

I have found a bug in YAHRmask. Calling YAHRmask with useawarp4=True results in a streak of black and white dots. I've made an image comparison for this purpose: https://slow.pics/c/Tnl72CAq

Sample Script:
import vapoursynth as vs
import fvsfunc as fvf
import muvsfunc as muf
core = vs.core

src = core.d2v.Source(r'oo_sample.d2v', rff=False)
src = fvf.Depth(src, 16)
#src = muf.YAHRmask(src, expand=10)
src = muf.YAHRmask(src, expand=10, useawarp4=True)
src = src.std.Crop(left=0, top=4, right=2, bottom=0)
src = src.resize.Spline36(1280, 720) #for image comparison
src = fvf.Depth(src, 10)
src.set_output()

Sample:
https://www.dropbox.com/s/hz4vep9jfarlk98/oo_sample.rar?dl=0

Tested on VS R58.

**Comment by WolframRhodium** [comment]
Thanks, I'll try to fix it later.
