### ISSUE TITLE
side note about core.misc.AverageFrames usage

### ISSUE THREAD

**Issue by Selur** [WolframRhodium/muvsfunc#61]
To reduce dependecies instead of `core.misc.AverageFrames` `core.std.AverageFrames` could be used on newer Vapoursynth versions.

**Comment by WolframRhodium** [comment]
The filter in the `core.std` namespace is indeed used.

https://github.com/WolframRhodium/muvsfunc/blob/713f207dde5206aa27b4e467a0db5472b3b4c2c1/muvsfunc.py#L1421-L1424

**Comment by Selur** [comment]
Ah sorry, I overlooked that somehow. :)
