### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by Helenerineium** [WolframRhodium/muvsfunc#7]
**In _numpy**, line 1352 should be `thr /= (2 ** bits) - 1` instead of `thr /= (2 ** bit) - 1`
IMHO, vs.core is better than vs.get_core(), and should be used as a drop-in replacement.

**Comment by Helenerineium** [comment]
Also, BMA III in the paper is Gaussian prior and Gaussian likelihood, IV is Gaussian prior and Laplacian likelihood, maybe another typo?

**Comment by WolframRhodium** [comment]
Thanks, they are all fixed now.

**Comment by Helenerineium** [comment]
Just see you typed **_gausssian_** instead of gaussian (BMA), thanks for all your work.
