### ISSUE TITLE
Seesaw

### ISSUE THREAD

**Issue by Helenerineium** [WolframRhodium/muvsfunc#8]
In function SeeSaw() line 2077: `Szrp = Szp / pow(Sstr, 0.25) / pow((ssx + ssy) / 2, 0.5)`
Szrp was not used anywhere (It should be szp)
Original avs code: `Szp = Szp / pow(Sstr, 1.0/4.0) / pow((ssx+ssy)/2.0, 1.0/2.0)`
Also, peak was not used in main function, only sharpen2 needs it.

**Comment by Helenerineium** [comment]
funcName is not defined in Compare2, so it will raise NameError if at least one of input is not a clip.

**Comment by WolframRhodium** [comment]
Fixed. Thank you.

**Comment by WolframRhodium** [comment]
Done. Thank you very much.
Sorry for my carelessness.

**Comment by Helenerineium** [comment]
Latest awarpsharp2 has a new parameter "cplace".
But the default is "mpeg1" to keep consistency with previous versions.
I think "mpeg2" would be a better choice when actually using it since it is more widely used.
But if you don't feel like changing it, that's fine.

**Comment by WolframRhodium** [comment]
I have noticed the change.
Currently, awarpsharp() in my scripts always functions on GRAY, so I think there's no need to change it.

Anyway, I see filtering chroma-subsampled clip by awarpsharp() as nearly unnecessary, because both the spatial resolution of chroma and the computation are low. I always prefer to perform it on YV24.

**Comment by Helenerineium** [comment]
### My bad
But typically I won't upsample the chroma to full resolution if they're subsampled.
I will prefer to process it on GRAY individually.

**Comment by WolframRhodium** [comment]
Oh I mean something like fix chroma bleeding which does processes on GRAY.
I confuse it with KNLMeansCL.
