### ISSUE TITLE
SSIM

### ISSUE THREAD

**Issue by Helenerineium** [WolframRhodium/muvsfunc#9]
> This is an pseudo-implementation of SSIM downsampler with slight modification.

I take a look at the pseudo code of the algorithm and have some questions.
```
L ← subSample(convValid(H, P(s)), s)
L2 ← subSample(convValid(H², P(s)), s)
```
The original code convolves the image with an averaging filter of size s×s before downscaling, but yours didn't, is that intentional?

And I hope you can modify your code so that people can select the kernel they want when using fmtconv.

**Comment by WolframRhodium** [comment]
Yes, I do that intentionally.
> The function subSample(X, y) subsamples the image X at intervals of y, ...

Here `subSample` means nearest neighbour interpolation a.k.a. PointResize.

It can be verified that the following codes are equivalent.
```python
down1 = core.std.Convolution(src, [0, 0, 0, 0, 1, 1, 0, 1, 1]).resize.Point(w//2, h//2)
down2 = core.fmtc.resample(src, scale=0.5, sx=0.5, sy=0.5, kernel='box')
```

For the second request, you can simply use
```python
down = muvsfunc.SSIM_downsample(src, w, h, kernel='lanczos', taps=4)
```
or equivalently
```python
kwargs = dict(kernel='lanczos', taps=4)
down = muvsfunc.SSIM_downsample(src, w, h, **kwargs)
```

Please feel free to refer to the [tutorial of keyword arguments](https://docs.python.org/3/tutorial/controlflow.html#keyword-arguments).

**Comment by Helenerineium** [comment]
The current implementation of your SSIM downsampler always uses 'spline36' as the base when fmtconv was selected for downscaling.

I think Mitchell-Netravali (the vszimg default) or even **Gaussian** (though slower) is a better choice.

Please feel free to edit it if you want.

**Comment by WolframRhodium** [comment]
Done.

**Comment by Helenerineium** [comment]
For me, your solution is a bit counter-intuitive
There are two ways you can set the kernel for zimg (explicitly set kernel or through **args)
And only one way can be used to set kernel for fmtconv (through manually set **args)
But that's fine by me, so issue closed.

**Comment by WolframRhodium** [comment]
Thanks for your reminder, the problem is actually more severe.
In previous version, one was completely not able to switch the kernel when using fmtconv because the function's argument `kernel='Bicubic'` absorb the definition of kernel, but it was absent in the execution of `fmtc.resample`.

**Comment by Helenerineium** [comment]
That's exactly what I'm trying to tell you in the previous comments.
But it seems that you are not able to completely grasp what I mean due to my wordings or whatever.
It is working perfectly now. 💯
